### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kiolalis** [jaguillette/TimeExplorer#4]
I downloaded the code, I changed the api key in line 77, but the timeline doesn't loaded. Any help please?

Yannis

**Comment by jaguillette** [comment]
I've just realized that the README is out of date, so I've just updated that. If you just want to make a timeline, check out the project site here: https://jaguillette.github.io/fabulousTime/. If you want to mess around with the source code, the README now has more up to date instructions, and if those don't work, check the JS console in your browser and let me know what kind of errors it's giving you.

**Comment by kiolalis** [comment]
Thank you for info. I tried to host an instance both localhost and [here](http://users.sch.gr/marvla/fabulous/),  but the timeline doesn't load. Also, the JS Console of Chrome broswer does not show any error. Any more help, please?

Yannis

**Comment by jaguillette** [comment]
You don't have a Google Sheet set up to provide any data to the timeline. You need to set up your data in a Google Sheet set up the same way that you'd set one up for Timeline JS, then provide the Google Sheet ID as a GET parameter called `tl_sheet`. I tried that with the setup that you linked to, and it does work, it just needs data.

**Comment by kiolalis** [comment]
Thanks again. I also tried in my setup (complete URL [here](http://users.sch.gr/marvla/fabulous/index.html?tl_sheet=110U8KOB-LNrKNoN5ccVHL8o3ieclUDjhzkhCP2IFX0g)) and it works. In such a manner user has to put manually the tl_sheet GET parameter in the URL every time he wants to present a timeline. Is there a way to put the tl_sheet inside the code for permanent results? Or mutliple tl_sheet?
Sorry if I bother you, but I'm a newbie in coding.

Yannis

**Comment by jaguillette** [comment]
You have to set up the sheet ID in the URL initially, but that ID doesn't change, so you can bookmark that page or send a that link you added to students or other teachers just fine. If you want a shorter URL, I'd use a url shortener like bit.ly.

**Comment by kiolalis** [comment]
Ok. thanks a lot. Also, I will watch your project.
