### ISSUE TITLE
Dates between 1 and 99 common era misinterpreted

### ISSUE THREAD

**Issue by pleksusmail** [jaguillette/TimeExplorer#5]
Dates between 1 C.E. till 99 C.E. are displayed on the timeline in the twentieth century instead of the first century. **It looks like the script somehow interprets the range from 1 to 99 as years 1901-1999.** I tried inserting the dates in Google Sheets in different formats (eg. 0001-0099) but it does not help. In other words for two different dates like 29 and 1929 you get the same placemark location on the timeline. I need to put some first-century dates on my timeline please help!

**Comment by jaguillette** [comment]
I was able to find a fix for this issue, and tested it on an example timeline. The dates seem to be working properly now.

**Comment by pleksusmail** [comment]
I never said "thank you"! What a shame :-(
Please be assured I appreciate. It's great you fixed it.
