### ISSUE TITLE
A few items wrongly appearing as a single day

### ISSUE THREAD

**Issue by Ninjakitten** [jaguillette/TimeExplorer#6]
I really like your version of this, but I do have an issue -- three of my items, which have valid start and end dates and do show up the correct length when I use the sheet in Timeline.js, show up as a single day (Jan 1 of the correct year) in TimeExplorer. I can't find any way in which they're different than the other entries -- they do seem to have the correct format.

**Comment by jaguillette** [comment]
I'm glad you like it! Could you provide some examples of the dates that aren't working so I can try to reproduce the issue?

**Comment by Ninjakitten** [comment]
Sorry about the delay! These are the ones that aren't working:

2002/01/04 - 2002/01/15
2005/01/02 - 2005/01/04
2007/01/14 - 2007/01/19

In each case, they show up on the timeline as Jan 1 of the appropriate year. I do notice that all three of these both start and end in January of the same year they began, and none of my other entries (the working ones) do that. I have two that did the same thing in a July, and one in a June, and those all show up properly.  It's only the ones that began and ended in the same January, in my data. Unfortunately I don't have any that began and ended in any of the other nine months to compare also!

**Comment by jaguillette** [comment]
Sorry it took so long to get to fixing this, but I was able to reproduce and then address this issue, and in my tests it's no longer an issue. It was an issue limited to January because of some null checking that was too lazy.

**Comment by Ninjakitten** [comment]
It does appear to be fixed now. Thank you very much! :D
